trigger:
  - main

variables:
  # Azure Resource Manager connection created during pipeline creation
  azureServiceConnectionId: "d5edb66d-1e3d-45ec-b380-267eb57da0cc"

  # Web app name
  webAppName: "my-first-flsk-app"

  # Agent VM image name
  vmImageName: "ubuntu-latest"

  # Environment name
  environmentName: "my-first-flsk-app-environment"

  # Project root folder. Point to the folder containing manage.py file.
  projectRoot: $(System.DefaultWorkingDirectory)

  pythonVersion: "3.11"

stages:
  - stage: Build
    displayName: Build stage
    jobs:
      - job: BuildJob
        pool:
          vmImage: $(vmImageName)
        steps:
          - task: UsePythonVersion@0
            inputs:
              versionSpec: "$(pythonVersion)"
            displayName: "Use Python $(pythonVersion)"

          - script: |
              python -m venv antenv
              source antenv/bin/activate
              python -m pip install --upgrade pip
              pip install setuptools
              pip install -r requirements.txt
            workingDirectory: $(projectRoot)
            displayName: "Install requirements"

          - task: ArchiveFiles@2
            displayName: "Archive files"
            inputs:
              rootFolderOrFile: "$(projectRoot)"
              includeRootFolder: false
              archiveType: zip
              archiveFile: $(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip
              replaceExistingArchive: true

          - upload: $(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip
            displayName: "Upload package"
            artifact: drop

  - stage: Deploy
    displayName: "Deploy Web App"
    dependsOn: Build
    condition: succeeded()
    jobs:
      - deployment: DeploymentJob
        pool:
          vmImage: $(vmImageName)
        environment: $(environmentName)
        strategy:
          runOnce:
            deploy:
              steps:
                - task: UsePythonVersion@0
                  inputs:
                    versionSpec: "$(pythonVersion)"
                  displayName: "Use Python version"

                - task: AzureWebApp@1
                  displayName: "Deploy Azure Web App : $(webAppName)"
                  inputs:
                    azureSubscription: $(azureServiceConnectionId)
                    appName: $(webAppName)
                    package: $(Pipeline.Workspace)/drop/$(Build.BuildId).zip
  - stage: Test
    displayName: Test Site
    jobs:
      - job: RunTests
        pool:
          vmImage: $(vmImageName)
        steps:
          - task: UsePythonVersion@0
            inputs:
              versionSpec: "$(pythonVersion)"
            displayName: "Use Python $(pythonVersion)"
          - script: |
              python -m venv .env
              source .env/bin/activate
              pip install setuptools
              pip install -r requirements.txt

            # The displayName shows in the pipeline UI when a build runs
            displayName: "Install dependencies on build agent"
          - script: |
              echo "Waiting for the app to warm up..."
              sleep 180
            displayName: "Wait for deployment to stabilize"
          - script: |
              pytest -rA
            displayName: "Run tests"

          - script: |
              echo Deleting .env
              deactivate
              rm -rf .env
            displayName: "Remove .env before zip"
