version: '3.8'

services:
  webapp:
    image: artifactory.dso.sern.mil/tyler-test/webapp:$(Build.BuildId)
    container_name: webapp
    restart: always
    ports:
      - "5000:5000"
    environment:
      FLASK_ENV: production
      
